### ISSUE TITLE
Yooasset.WechatFileSystem.cs换行符混用

### ISSUE THREAD

**Issue by RookieLucas** [GameFrameX/GameFrameX#15]
There are inconsistent line endings in the 'Packages/com.gameframex.unity.tuyoogame.yooasset/Runtime/FileSystem/WechatFileSystem/WechatFileSystem.cs' script. Some are Mac OS X (UNIX) and some are Windows. This might lead to incorrect line numbers in stacktraces and compiler errors.

**Comment by AlianBlank** [comment]
已经修复。更新到最新的package 即可
